services:
  backend:
    build: ./app/backend
    container_name: pyback
    network_mode: "host"
  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./app/frontend/html:/var/www/html
      - ./app/frontend/nginx/sites-available:/etc/nginx/sites-available
      - ./app/frontend/nginx/conf.d:/etc/nginx/conf.d
