services:
  backend:
    build: ./app/backend
    container_name: pyback
    network_mode: "host"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    network_mode: "host"
    volumes:
      - ./app/frontend/html:/var/www/html
      - ./app/frontend/nginx:/etc/nginx/sites-available
